import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import fg from 'fast-glob';

import {
  buildSchemaFromFiles,
  type ExtractedField,
  type ExtractedSchema,
} from '../extractor/schemaBuilder';

export interface ExtractOptions {
  /** Project root (where apps/ and packages/ live). */
  rootDir: string;
}

/**
 * Extract DevCMS schema from a repo by scanning for `useCMS()` and `<Inline*>`.
 */
export async function runExtract(options: ExtractOptions): Promise<ExtractedSchema> {
  const rootDir = options.rootDir;

  const patterns = [
    'apps/**/*.ts',
    'apps/**/*.tsx',
    'packages/**/*.ts',
    'packages/**/*.tsx',
    '!**/node_modules/**',
    '!**/.next/**',
    '!**/dist/**',
  ];

  const files = await fg(patterns, { cwd: rootDir, absolute: true });
  const schema = await buildSchemaFromFiles(files);

  const cmsDir = path.join(rootDir, 'cms');
  await mkdir(cmsDir, { recursive: true });

  await writeFile(path.join(cmsDir, 'schema.json'), JSON.stringify(schema, null, 2) + '\n', 'utf8');
  await writeFile(path.join(cmsDir, 'schema.d.ts'), generateTypes(schema), 'utf8');

  return schema;
}

function generateTypes(schema: ExtractedSchema): string {
  const keySet = new Set(
    schema.fields.map((f: ExtractedField) => `${f.namespace ?? 'default'}:${f.path}`),
  );
  const keys: string[] = Array.from<string>(keySet).sort();

  const keyUnion =
    keys.length === 0 ? 'never' : keys.map((k) => `'${k.replace(/'/g, "\\'")}'`).join(' | ');

  return [
    '// Generated by DevCMS CLI – do not edit by hand.',
    '/* eslint-disable */',
    '/* prettier-ignore */',
    '',
    `export type DevCMSKey = ${keyUnion};`,
    '',
  ].join('\n');
}

